project:
  type: website

website:
  title: "Anna Haroutounian"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects/
        text: Projects
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    toc: true



